spring.application.name=TF_TP1_Backend
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/TrabajoFinal_TP1
spring.datasource.username=postgres
spring.datasource.password=peru260604
server.port=8080
jwt.secret=85f82dffb38fe51f1fe2957b9c04ac33d9d8376488e14e8e07dfa134fb7675499d323e44447ed3d7b12eb2d8c2f44de20386529fcb797e5ea84273624cf37788
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
modelo.ipress.url=${MODELO_IPRESS_URL:http://localhost:8000}
